.github/oidc/setup.sh
fixing bug found in oidc setup script. 
N/A
=> Fix typo with oidc setup script

package.json
Changing release branch to production 
#Close #https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/216?modal=detail&selectedIssue=OY2-21204
Change release stage to production
=> fix(semantic release) : change release branch to production

.github/workflows/security-hub-sync.yml, src/run.ts
This feature will allow us visibility to medium security hub sync findings 
Closes #33 
I added the severity of medium to the security hub sync
=> Add medium severity to security hub sync

src/libs/connect-lib.js, src/services/seatool/serverless.yml
Update our http requests code to handle an error thrown on the req object.
https://qmacbis.atlassian.net/browse/OY2-21920
Added handling for req.on("error")
https://stackoverflow.com/a/8381820/1260955
We were handling res.on("error"), but not req.on("error") which is not the same.
=> Add error handling on http.request

src/services/alerts/serverless.yml
We needed to create kms keys to encrypt unencrypted sns topics 
Closes #50 
This changes the encrypt the sns topic created from this repo
=> Created KMS Key and encrypted SNS Topic 

.github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/pre-commit.yml, .github/workflows/running-stage-notifier.yml, .github/workflows/security-hub-sync.yml, package.json, src/run.ts, yarn.lock
Add running stages notifier and update github action versions
=> Add running stages notifier and update github action versions

docs/docs/services/alerts.md, docs/docs/services/compare.md, docs/docs/services/status.md
Updating the docs site to include the updates and changes made in [this ticket](https://qmacbis.atlassian.net/browse/OY2-21832)
https://qmacbis.atlassian.net/browse/OY2-21833
=> Add Docs for compare updates

docs/_deploy-metrics/yarn.lock, package.json, src/libs/package.json, src/libs/yarn.lock, src/services/compare/yarn.lock, src/services/connector/yarn.lock, src/services/dashboard/yarn.lock, yarn.lock
=> chore(deps): Update Dependencies

src/run.ts, src/services/compare/handlers/stopExecutions.ts, src/services/compare/package.json, src/services/compare/serverless.yml, src/services/compare/yarn.lock
Add custom resource to stop state machine executions on destroy.
https://qmacbis.atlassian.net/browse/OY2-22919
Remove custom stop-execution script in compare service and associated script plugin.
Add custom resource that runs stopExecution lambda which checks for running executions and kill them on destroy event.
N/A
=> feat(custom-stop): Add custom resource to stop state machine executions on destroy

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/auto-create-pr-production.yml, .github/workflows/auto-create-pr-val.yml, .github/workflows/cfn-nag.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/running-stage-notifier.yml, .github/workflows/security-hub-sync.yml, src/services/dashboard/serverless.yml
Applying the latest updates from our MACPRO base template
1. Updated GitHub PR template
2. Auto create environment promotion PRs
3. Add cfn-nag GitHub Actions Workflow
4. Improvements to other workflows
=> feat(update-from-base): Applying the latest updates from our MACPRO base template

.github/workflows/cfn-nag.yml, src/services/connector/serverless.yml, src/services/dashboard/serverless.yml
Minor fixes to make cfn-nag happy, updated CloudFormation for implicit security group egress to be explicit.
Unrelated to cfn-nag, changed !Sub to !Ref where a string is not being created using multiple variables.
=> fix(cfn-nag): Minor fixes for cfn-nag

.github/actions/setup/action.yml, .github/workflows/dependency-update.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/running-stage-notifier.yml, .github/workflows/security-hub-jira-sync.yml, package.json, src/run.ts, src/runner.ts, src/services/alerts/serverless.yml, src/services/appian/serverless.yml, src/services/compare-appian/serverless.yml, src/services/compare-mmdl/serverless.yml, src/services/connector/serverless.yml, src/services/dashboard/serverless.yml, src/services/mmdl/serverless.yml, src/services/seatool/serverless.yml, src/services/status-appian/serverless.yml, src/services/status-mmdl/serverless.yml, yarn.lock
Updating from base template. Changes include node runtime update to v18 and deploy workflow improvements.
=> feat(base updates): Updating from base template

src/services/compare-appian/handlers/workflowStarter.ts, src/services/compare-appian/serverless.yml, src/services/compare-mmdl/handlers/workflowStarter.ts, src/services/compare-mmdl/serverless.yml
Add workflowStatus Param
N/A
We want to be able to initiate the service without starting workflows. So we are using a sls param value. sls param values are always strings so although a boolean would be more readable, 'ON' and 'OFF' are used instead.
=> Add workflowStatus Param

docs/_deploy-metrics/yarn.lock, src/libs/yarn.lock, src/services/compare-appian/yarn.lock, src/services/compare-mmdl/yarn.lock, src/services/connector/yarn.lock, src/services/dashboard/yarn.lock, yarn.lock
=> chore(deps):  Upgrade all node dependencies

src/services/compare-appian/handlers/initStatus.ts, src/services/compare-appian/serverless.yml
Squashing some bugs after review.
N/A
=> fix(appian init): Fix appian init step

src/services/compare-mmdl/handlers/sendNoMatchAlert.ts, src/services/compare-mmdl/handlers/utils/getEmailContent.ts, src/services/compare-mmdl/serverless.yml, src/services/connector/serverless.yml
Updating alert content and adding deleteItem perm to connector service
https://qmacbis.atlassian.net/browse/OY2-23282
This change adds seatool url as a stage param to be used in the alert email. Additionally this adds the deleteItem permission to the connector service to fix bug when sink functions need to delete items.
=> fix(alert content): updating alert content

src/services/compare-mmdl/handlers/sendNoMatchAlert.ts, src/services/compare-mmdl/handlers/sendReport.ts, src/services/compare-mmdl/handlers/utils/getEmailContent.ts, src/services/compare-mmdl/handlers/utils/getIsIgnoredState.ts, src/services/compare-mmdl/serverless.yml, src/services/connector/handlers/utils/getMmdlInfoFromRecord.ts, src/types/mmdl/interfaces.ts
This change adds the functionality to be able to ignore state codes. This will primarily apply in the production environment. Also found a big ole bug along the way. Squashing it.
https://qmacbis.atlassian.net/browse/OY2-23338
We have added a stage param in the mmdl-compare service to list state codes that should be ignored. Utility added to handle the logic. Added column to report data to show if record alerts would be ignored. 
N/A
=> feat(ignored states): Add func to ignore certain test states

src/services/compare-appian/handlers/initStatus.ts, src/services/compare-appian/handlers/seatoolRecordExist.ts, src/services/compare-appian/handlers/workflowStarter.ts
Adjusted logic to account for new database keys. Verified that the step functions worked with adjusted logic
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/240?modal=detail&selectedIssue=OY2-23320
=> fix(appian-compare): adjusted logic to include PK and SK when querying the database

.github/workflows/auto-create-jira-comment.yml, .github/workflows/dependency-update.yml, .github/workflows/deploy.yml, .github/workflows/destroy.yml, .github/workflows/running-stage-notifier.yml, .github/workflows/security-hub-jira-sync.yml, .github/workflows/workspace-setup.yml, docs/docs/workflows/auto-create-jira-comment.md, docs/docs/workflows/security-hub-jira-sync.md, package.json, src/run.ts, src/services/dashboard/handlers/templatizeCloudWatchDashboard.ts, src/services/dashboard/templateDashboard.txt, yarn.lock
General maintenance. Updating from base-template. This change cleans up the dashboard implementation, adds jira commenting integration. Updates some github action packages and adds documentation. 
N/A
=> chore(base update): update from base repo

docs/docs/services/appian.md, docs/docs/services/compare-appian.md, docs/docs/services/compare-mmdl.md, docs/docs/services/status-appian.md
Made some small changes to compare-appian documentations
https://qmacbis.atlassian.net/jira/software/c/projects/OY2/boards/240?modal=detail&selectedIssue=OY2-23469
=> fix(docs): small doc updates for compare appian service

src/services/compare-appian/handlers/compare.ts, src/services/compare-appian/handlers/sendReport.ts, src/services/compare-appian/handlers/tests/compare.test.ts, src/services/compare-appian/handlers/tests/getAppianData.test.ts, src/services/compare-appian/handlers/tests/initStatus.test.ts, src/services/compare-appian/handlers/tests/seatoolRecordExist.test.ts, src/services/compare-appian/handlers/tests/sendNoMatchAlert.test.ts, src/services/compare-appian/handlers/tests/sendReport.test.ts, src/services/compare-appian/handlers/tests/stopExecutions.test.ts, src/services/compare-appian/handlers/tests/updateStatus.test.ts, src/services/compare-appian/handlers/tests/workflowStarter.test.ts, src/tests/vitest.config.ts
Adds unit tests for the `compare-appian` handlers.
[OY2-23129](https://qmacbis.atlassian.net/browse/OY2-23129)
=> feat(compare-appian): Add unit tests for compare-appian handlers

src/services/compare-mmdl/handlers/sendNoMatchAlert.ts, src/services/compare-mmdl/handlers/tests/sendNoMatchAlert.test.ts, src/services/compare-mmdl/handlers/utils/getEmailContent.ts, src/services/dashboard/templateDashboard.txt
This change updates the CloudWatch dashboard to correctly track application health.
Additionally this removes some unwanted text from the mmdl alert emails 
Dashboard: https://qmacbis.atlassian.net/browse/OY2-23591
Text Change: https://qmacbis.atlassian.net/browse/OY2-23128
The CloudWatch dashboard was updated by configuring the dashboard as I wanted it in the UI, running the template export widget from the dashboard, and checking in the source it output.
dashboard screenshot included
=> feat(dashdoard): Update metrics dashboard

docs/_deploy-metrics/yarn.lock, src/libs/yarn.lock, src/services/compare-appian/yarn.lock, src/services/compare-mmdl/yarn.lock, src/services/connector/yarn.lock, src/services/dashboard/yarn.lock, yarn.lock
Reverts Enterprise-CMCS/seatool-compare#147
=> Revert "chore(deps):  Upgrade all node dependencies"

src/services/compare-mmdl/serverless.yml
Turn on wf's for higher environments
=> fix(wfs): turn on mmdl compare workflows

src/services/compare-mmdl/handlers/sendReport.ts, src/services/compare-mmdl/handlers/utils/getEmailContent.ts, src/services/compare-mmdl/serverless.yml, src/services/connector/handlers/sinkMmdlData.ts, src/services/connector/handlers/tests/sinkMmdlData.test.ts, src/types/mmdl/interfaces.ts
=> fix(mmdl-key): update mmdl key with tn

src/services/compare-mmdl/handlers/getMmdlData.ts, src/services/compare-mmdl/handlers/workflowStarter.ts
We adjusted the PK to include logic to trim whitespace and replace blank characters with dashes. Occasionally transmittal numbers are inputted without the correct format, we added some logic to catch these issues.
https://qmacbis.atlassian.net/browse/OY2-24394
We reached out to the MMDL team to check if validations are being done on their end, they should have transmittal number validations into production by 6/23
=> fix(workflow-starter): adjust PK with trim and regex to stepflow name

src/services/compare-appian/handlers/getAppianData.ts, src/services/compare-appian/handlers/sendNoMatchAlert.ts, src/services/compare-appian/handlers/sendReport.ts, src/services/compare-appian/handlers/tests/getAppianData.test.ts, src/services/compare-appian/handlers/tests/getStartAtTmeStamp.test.ts, src/services/compare-appian/handlers/tests/sendReport.test.ts, src/services/compare-appian/serverless.yml, src/services/compare-mmdl/serverless.yml, src/types/appian/interfaces.ts
Add Appian compare logic into master following Padma's testing
https://qmacbis.atlassian.net/browse/OY2-24294
Padma tested and found a few edge cases which we have logged on the backlog
Logged tickets https://qmacbis.atlassian.net/browse/OY2-24614 and https://qmacbis.atlassian.net/browse/OY2-24613 for spacing and case sensitive issues.
=> feat(appian-alertting): added logic to fix alert

src/services/compare-appian/serverless.yml
Adjust the sinceSubmissionTime to the correct cadence to alert at 4 days at the start of alerting.
=> fix(appian-alerts)change since submission time minimum time alerts

src/services/compare-appian/serverless.yml
Change workflow status to on in upper environments (val)
=> fix(workflow-status): update workflow to fire in val

src/services/compare-appian/handlers/sendReport.ts
Added logic to only pull records for packages in submission status
=> fix(appian-reports): Updated report logic to filter for submitted status packages

src/services/compare-appian/handlers/sendReport.ts
Added column to show when a appian record exists
=> fix(appian-report): add requested appian exist column

src/services/compare-appian/handlers/sendReport.ts
Update the Send Report logic of filter on IS_CRNT_VRSN
=> fix(appian-reports): Update sendReport to account for final versions 

src/services/compare-appian/handlers/sendReport.ts
remove logs from appian reporting
=> fix(report-cleanup): remove logs from appian reporting

src/services/compare-appian/handlers/sendReport.ts
changed logic to fix date formats on appian reports
=> fix(appian-reports): changed logic to fix date formats on appian reports
